with open('/Users/Paul.Chernoch/Documents/GitHub/paulchernoch/source/synopsis.yaml', 'r') as f:
    content = f.read()

updates = [
    ("riddle-of-153-fish.md",
     "John 21's account of the disciples catching exactly 153 large fish has puzzled Christians for nearly two thousand years — this article introduces the riddle and points to the broader investigation that unravels its meaning. The scene is rich with symbolism: the disciples catching nothing all night until Jesus appears at sunrise, the net that holds 153 fish without tearing, and the charcoal breakfast Jesus prepares on the shore. To find the answer, readers are directed to the numerology section of the site where connections between 153, Noah's Flood, the prophet Habakkuk, and the trumpets of Revelation converge into a single answer. The article serves as a gateway into one of the most surprising and mathematically elegant discoveries in all of the author's biblical research."),

    ("riddles-of-war.md",
     "Proverbs 30, positioned as the penultimate chapter of the book and corresponding to the time of war (2160-2280 AD) in Solomon's Growth Pattern, is decoded as God's battle plan for the final conflict between good and evil hidden in plain sight. The chapter's distinctive literary form — counting similar things and then listing them — provides the structural key: thirteen numbered sayings about ants, coneys, locusts, lizards, and other creatures encode military tactics and the moral forces at play in history's final war. The chapter's explicit self-identification as an oracle and its admission that the writer lacks wisdom (Proverbs 30:3) bracket the material as a riddle deliberately composed beyond normal comprehension. The article deciphers this riddle by cross-referencing it with Revelation and other prophetic texts, revealing a vision of God's decisive intervention on behalf of the righteous against Leviathan and the final beast."),

    ("riddles.md",
     "This article introduces a special category of biblical puzzle called Emotional Riddles — passages deliberately worded to provoke anger, despair, confusion, or shame in the reader, thereby concealing their deepest wisdom from the hostile or impatient heart. God designs some riddles this way because only those who persevere through the emotional barrier (who press through fear, humiliation, or offense) will discover the treasure on the other side — a technique that mirrors the biblical principle that the glory of kings is to search out what God has concealed. Three examples are explored: the Fear of the Lord (which sounds terrifying to abuse survivors), the proverb about not being overly righteous (which seems to endorse mediocrity), and Samson's honey riddle (whose solution cost his first wife her life). The article argues that emotional resilience, more than intellectual ability, is the key that unlocks the Bible's deepest treasures."),

    ("roof-of-peace.md",
     "This article explains how Paul's seven letters form the roof of Lady Wisdom's House — the capstone of the entire biblical wisdom structure — by providing the fullest account of how peace with God, self, and neighbor is achieved through Christ. The author traces his personal journey through four books: identifying heavenly treasures (The Endless Hunt), confronting loss and mourning (Job Rises), mapping the path to peace through Solomon (Peace, like Solomon Never Knew), and exploring God's justice and peace through the Law and Psalms (Plague, Precept, Prophet, Peace). The roof of peace fits atop the seven pillars because both the Harvest Pattern (ending in peace) and the Growth Pattern (ending in loyalty that produces peace) point skyward toward the same destination. Paul's seven letters from Romans to Colossians function as the architect's final design: each letter addresses one growth phase, building the believer from eternal security in Romans to complete loyalty in Colossians."),

    ("salvation.md",
     "This article presents a landmark discovery: twelve separate passages in the Bible each enumerate the complete Order of Salvation in the same sequence, resolving a centuries-old theological debate about the Ordo Salutis. The passages range from the Ten Commandments (Exodus 20) to Job's nine speeches, Elihu's speech, God's speech to Job, Psalm 19, Proverbs 1-9, the Beatitudes, the full Sermon on the Mount, John 17, Paul's letters to churches, and Ephesians 4 — all presenting nine to twelve steps from Calling through Glorification in essentially the same order. The discovery strongly corroborates the Reformed Order of Salvation, with the main differences being the optional inclusion of Election and Predestination at the beginning and a swap between Salvation and Adoption. The article maps the salvation process into three phases (Seeker, Believer as servant, Son in full inheritance), making visible the complete arc of God's saving work in a single person's life."),

    ("satan-s-taunt.md",
     "This article solves the riddle of why Satan chose to quote Psalm 91 when tempting Jesus in the desert — and finds the answer laced with irony, because Psalm 91 is the very psalm that prophesies Satan's binding and defeat. Psalm 91 is the thirteenth triangular psalm (91 = 1+2+...+13) and its thirteenth verse — 'You will tread on the lion and the cobra; you will trample the great lion and the serpent' — is the key to understanding what the devil was inadvertently confessing by quoting it. The article situates Psalm 91 within the broader context of the author's discovery that triangular-numbered psalms carry special prophetic significance, a pattern that also links Habakkuk (structured around the seventh triangular number, 28) to the miraculous catch of 153 fish (the seventeenth triangular number). Satan's selective quotation of the psalm was intended to trap Jesus but instead announced the very sentence that would fall on Satan when Christ completed his mission."),

    ("secret.md",
     "This page collects the website's most intriguing biblical riddles into a single spoiler-protected gallery, inviting visitors to guess the answer before revealing it with a click — a playful entry point into deeper articles. Riddles covered include: the meaning of the number 42 (the gematria of God's name Eloah, and the answer to the meaning of life), the identity of the wisest woman in the Bible (Hannah), why the disciples caught 153 fish, when Satan was bound (already, in 380 AD) and unbound (a thousand years later), what the Seven Pillars of Wisdom are (seven specific Bible books), and whether the sealed message of the Seven Thunders in Revelation 10 can be decoded (yes, because they spoke before in Exodus, Job, and the Psalms). Each riddle links to the full article where the answer is developed with detailed textual analysis and historical evidence. The page is designed to spark curiosity and draw in readers who might not know where to begin in such a large library of material."),

    ("seven-cycles-of-judgment.md",
     "This article maps the seven bowl judgments of Revelation 16 to the Seven Spirits of God from Isaiah 11:2, showing that each spirit instigates a different category of divine judgment against the world in the sequence given by Isaiah. The Seven Spirits — the Spirit of the Lord, Wisdom, Understanding, Counsel, Might, Knowledge, and the Fear of the Lord — are each matched to one of the seven pillar books, one phase of the Harvest Pattern, and one divine judgment, all in the same canonical order. The analysis reveals a surprising unity between the structure of Lady Wisdom's House (built by the seven spirits) and the structure of the world's destruction (dismantled by the same seven spirits in their last great outpouring). The article ends by observing how the final earthquake of the seventh bowl flattens every house not built on the rock of God's law — a direct echo of Jesus' parable at the close of the Sermon on the Mount."),

    ("seven-pillars-of-wisdom.md",
     "This article tells the story of how the author discovered the Seven Pillars of Wisdom — the seven Bible books Psalms, Job, Proverbs, Song of Songs, Ecclesiastes, Matthew, and Revelation — not by searching for them deliberately, but by following the Holy Spirit's guidance through decades of immersion, suffering, and mystical experience. The discovery came only after each pillar had been buried deep through painful longing, fed by imagination through poetry and fiction, and studied with exactitude — the Spirit's way of preparing the scholar before unveiling the whole. The seven books are unified by a set of connections that no other books share: all conform to both the Harvest Pattern and the Growth Pattern, and all are ordered according to the Harvest Pattern's sequence. The article describes the practical message of each pillar — what wisdom each book is designed to produce in the believer — and invites readers to begin their own journey through the house whose foundation is the Law and whose roof is peace."),

    ("seven-pillars-riddle.md",
     "This article answers the ancient riddle of Proverbs 9:1 — 'Wisdom has built her house; she has hewn her seven pillars' — by identifying the seven pillars as seven specific Bible books: Psalms, Job, Proverbs, Song of Songs, Ecclesiastes, Matthew, and Revelation. What distinguishes these seven from all other Scripture is that they uniquely conform to both the Harvest Pattern of Jesus and the Growth Pattern of Solomon, making them the structural pillars of a comprehensive wisdom system. The article describes the practical wisdom that each pillar book is designed to impart — from Psalms teaching reverence and security in God, to Job teaching endurance through suffering, to Revelation teaching the Fear of the Lord that completes wisdom. The first prophet to announce the existence of these seven pillars was Hannah, whose prayer in 1 Samuel 2 contains the phrase 'the barren has borne seven' paired with 'the pillars of the earth are the Lord's' — both references pointing to this same set of books."),

    ("seven-spirits.md",
     "The Seven Spirits of God in Revelation — identified with the seven spiritual qualities listed in Isaiah 11:2 — are matched to the seven pillar books of the Bible and the seven phases of the Harvest Pattern, revealing a coherent theology of how the Holy Spirit works through Scripture to transform believers. Each spirit illuminates one pillar book like a torch mounted on a pillar: the Spirit of the Lord illuminates Psalms, Wisdom illuminates Job, Understanding illuminates Proverbs, Counsel illuminates Song of Songs, Might illuminates Ecclesiastes, Knowledge illuminates Matthew, and the Fear of the Lord illuminates Revelation. The article traces four major historical sendings of the Seven Spirits into the earth, showing that God deploys them in the canonical order of Isaiah 11 and that each sending corresponds to a new era of spiritual awakening in church history. The beauty of this ordering is that the pillar books were arranged in this same sequence by Jesus' Harvest Pattern before the spirits were matched to them — providing independent confirmation that the selection and ordering of the pillars is correct."),

    ("seven-thunders.md",
     "This article tackles one of the Bible's most enigmatic puzzles: the Seven Thunders of Revelation 10, whose message John was told to seal up and not write down. The author's discovery is that the Seven Thunders have spoken before — in the seven thunder Psalms (18, 29, 68, 77, 81, 93, and 104), in the seven plagues of thunder in Exodus, and in Job — and that their repeated message can be assembled from these prior appearances even though John's specific vision remains sealed. The seven prior thunderings, each associated with one of the Seven Spirits and one phase of the Harvest Pattern, collectively describe a song that will be sung at the final victory: a song of glory, salvation, worship, miracle, praise, gospel proclamation, and resolution. The article argues that God did not forbid knowledge of the thunders' content but rather transferred the revelation to earlier texts that were left unsealed — a pattern consistent with his practice of giving the same revelation to multiple prophets across the centuries."),

    ("sojourn-of-israel.md",
     "This article works out the chronology of Israel's sojourn in Egypt — determining when it began, when the 400 years of affliction started, and when the 430 years of total residence ended — as a necessary foundation for solving the riddle of Job's Anti-Jubilee Clock. The analysis treats the Bible like a Sudoku puzzle: many date-cells have been erased, but by assembling all the biblical constraints (elapsed times, genealogical counts, and cross-references), the missing dates can be recovered. The article carefully distinguishes between the total 430 years of sojourning (counting from Abraham's departure from Haran) and the 400 years of affliction (counting from when Ishmael mocked the newly weaned Isaac), harmonizing otherwise conflicting texts in Genesis, Exodus, and Galatians. The conclusion places the sojourn from 1877 BC to 1447 BC, which anchors the subsequent calculation of the Anti-Jubilee Clock hidden in Job."),

    ("solomon-s-countdown-timer.md",
     "Solomon's twenty-eight times in Ecclesiastes 3 are revealed to be not only a map of human life but also a countdown clock for world history, with each time corresponding to a 120-year era from 960 BC to approximately 2280 AD, when the age of peace is expected to arrive. The article presents a detailed table matching each of the twenty-eight times to specific historical events — from Israel's civil war at the time of being born (960 BC) to the expected return of Christ at the time for peace (2280 AD) — demonstrating the pattern's prophetic accuracy across thirty-three centuries. The mathematical beauty of the number twenty-eight (simultaneously a triangular and perfect number matching the sidereal month) is shown to be intentional: Habakkuk used 28 as the seventh triangular number to structure his prophecy, and Solomon used the same number as the mainspring of history's clock. This countdown timer is the master framework for all of the prophetic clocks explored on the website."),

    ("spiritual-growth.md",
     "This section introduction surveys the full range of spiritual growth articles on the website, introducing five patterns that govern how Christians develop from infancy to full maturity: the Harvest Pattern (Jesus), the Growth Pattern (Solomon), the Motherhood Pattern (Job and 1 Samuel), the Law Pattern (Moses), and the Journey Pattern (Matthew and Job). The author explains why Jesus used agricultural analogies for spiritual growth: because the same principles that govern the growth of plants from seed to harvest also govern the growth of individuals, churches, nations, and civilizations — making prophecy possible and history interpretable. A key argument is that Solomon's statement that 'no progression of thought from one section to another is discernible' in Ecclesiastes (quoted from a scholarly commentary) is wrong: the twenty-eight times are perfectly ordered to describe human development from birth to maturity. This introduction frames all the articles in the Spiritual Growth section as tools for understanding and cooperating with God's design for the seasons of a human life."),

    ("spiritual-warfare.md",
     "This comprehensive article on spiritual warfare begins by arguing that the most important preparation for battle is to understand spiritual growth — because the enemy's goal is to stop that growth, and understanding what he is attacking is the first step to defending it. The Great Commandment (love God with all your heart, soul, mind, and strength; love your neighbor as yourself) provides the framework: spiritual warfare is ultimately the defense of the capacity to love, which the enemy attacks on five battlefields (heart, soul, mind, strength, and community). The article then marshals the full toolkit of Lady Wisdom's House — the Harvest Pattern, the Growth Pattern, the Seven Spirits, the Seven Pillars, the Law of Christ, and the Whole Armor of God — as integrated resources for both understanding and winning the spiritual battle. Practical guidance is grounded in the author's personal experience with nightmares, depression, anxiety, and temptation, offering hard-won wisdom for believers under siege."),

    ("submission.md",
     "This article, the third in the women's ordination series, argues that the long suffering of Christian women across the centuries — like that of the author's church member Janet Sullivan, whose rheumatoid arthritis could not diminish her spiritual radiance — constitutes a collective ordination sacrifice that qualifies women for full church ministry. The mysterious verse of 1 Timothy 2:15 — 'she will be saved through The Childbearing, if they continue in faith and love and holiness' — is interpreted not as individual women being saved by bearing children, but as a group of women (the church) being saved through a special Childbearing event, which the author identifies with the Protestant Reformation. The emphasis on faith, love, holiness, and sound-mindedness as the conditions points to a sacrificial ordination, not biological reproduction. The article ends with the question of what exactly The Childbearing is, setting up the following articles in the series to answer it through the framework of prophetic clocks."),

    ("talk-to-god.md",
     "This article catalogs nearly every permissible means of human communication with God — and God's communication back to humans — as found hidden throughout the Book of Job, arguing that Job's comprehensive treatment of this subject makes it the Bible's definitive 911 call center. The means are divided into three eras: those available before Jesus' birth (dreams, visions, angels, nature, wise elders, lots, prayer), those available during Jesus' earthly ministry, and those given to the church at Pentecost (the Holy Spirit, tongues, prophecy, healing). The discovery was motivated by the author's experience of finding a rainbow at the end of an exhausting day of family crises — God's wordless communication that He is present and eager to talk. The article closes with a practical exhortation: employ the ordinary means of communication consistently, pray for the extraordinary ones, and trust that God will speak in the way best suited to your need."),

    ("the-beatitudes.md",
     "The Beatitudes of Matthew 5 are revealed to be far more than scattered blessings for different personality types — they are Jesus' precise, nine-step answer to King David's prayer for salvation in Psalm 19, arranged in the same order as the Reformed Ordo Salutis (Order of Salvation) and conforming to the Harvest Pattern. Each beatitude corresponds to one step of salvation: from Calling (poor in spirit) through Regeneration (mourning), Faith (meekness), Repentance (hunger and thirst for righteousness), Justification (mercy), Sanctification (pure in heart), Adoption (peacemakers), Perseverance (persecuted for righteousness), and Glorification (reviled and blessed). The Beatitudes also serve as a table of contents for the entire Sermon on the Mount in reverse chiastic order, linking each blessing to a corresponding teaching in the sermon. God's prophetic plan, the article argues, was to unveil each doctrine of salvation with power in a specific historical era, delivering to the church its nine blessings in sequence — with one last blessing (glorification) yet to come."),

    ("the-childbearing.md",
     "This article tackles the most theologically vexed verse in the women's ordination debate — 1 Timothy 2:15, 'But she will be saved through The Childbearing' — by surveying dozens of English translations to expose the translators' own uncertainty about who is being born and who is doing the saving. Three candidate identities for the child emerge from the translations: ordinary babies, the Christ child, or a figurative birth of something else entirely. The author argues for the third interpretation: The Childbearing is a singular redemptive event — the Protestant Reformation — whose birth pangs transformed the status of women in the church and Western civilization over five subsequent centuries. The peculiar grammar of the verse (she singular being saved by what they plural do) is a key clue that this is not about individual women surviving childbirth but about a corporate act that saves a collective group. This article sets up the detailed historical and prophetic argument developed in the subsequent articles of the women's ordination series."),
]

count = 0
for source, synopsis in updates:
    old = f"  source: {source}\n  synopsis: No synopsis yet"
    new = f"  source: {source}\n  synopsis: {synopsis}"
    if old in content:
        content = content.replace(old, new, 1)
        count += 1
    else:
        print(f"WARNING: could not find placeholder for {source}")

with open('/Users/Paul.Chernoch/Documents/GitHub/paulchernoch/source/synopsis.yaml', 'w') as f:
    f.write(content)

print(f"Updated {count} synopses.")
remaining = content.count('No synopsis yet')
print(f"Remaining placeholders: {remaining}")
