import re

with open('/Users/Paul.Chernoch/Documents/GitHub/paulchernoch/source/synopsis.yaml', 'r') as f:
    content = f.read()

updates = [
    ("golden-rule.md",
     "The Golden Rule of Jesus (Matthew 7:12) is explored not as a simple ethical maxim but as a profound teaching requiring deep inner transformation before it can be genuinely practiced. Sandwiched between the ask-seek-knock passage and the narrow gate, it reveals that loving your neighbor as yourself demands changes to mind, heart, and hands — and that God himself must supply the resources needed to live it. The author traces his own decades-long journey of failure and growth, from trying and failing to follow Bonhoeffer's radical standard, to depression, pride, and wrong values, and eventually a discovery of how to live generously by relying on God's supply. The Golden Rule is not a beverage drunk once and forgotten but a spring returned to again and again, yielding new insight at every stage of life."),

    ("grandfather-clock.md",
     "A prophetic clock hidden in Ecclesiastes maps all of world history to three phases of human life: ascending years (4020 BC to 880 AD), productive years (880 to 2080 AD), and declining years (2080 to 2280 AD), followed by the end of history. Drawing on Solomon's tripartite structure of Ecclesiastes — twenty-eight lifetimes in chapters 1-10, productive-years material in chapters 10-11, and the fading-of-faculties imagery in chapter 12 — the author shows how major developments in Western Civilization fall into their correct centuries. The silver cord of Ecclesiastes 12:6, interpreted as the invisible thread tethering soul to body, becomes the symbol for history's end when it is finally severed. This Grand Father Clock is one of the most sweeping of all the prophetic clocks identified in the author's research."),

    ("growth-pattern.md",
     "Solomon's Growth Pattern, drawn from the twenty-eight times of Ecclesiastes 3 organized into seven groups of four, is the author's most important discovery — the framework that unifies his understanding of discipleship, human development, and prophetic history. As a human developmental model, its seven phases span birth to full maturity, each with its characteristic challenge; as a discipleship model, Paul's first seven letters from Romans through Colossians match each phase in sequence; as a prophetic framework, it governs all of history at multiple scales simultaneously. The pattern explains why Solomon was the wisest man in history: he mapped out all the steps from birth to maturity without missing a single one. This article introduces the Growth Pattern and points to companion articles that explore its application to discipleship and to prophecy."),

    ("habakkuk-part-1.md",
     "The Book of Habakkuk is mathematically structured in seven sections whose element counts form the seventh triangular number (1+2+3+4+5+6+7=28), proving that triangular numbers were intentionally woven into prophetic writing by Old Testament authors. The first section (Habakkuk 1:1-4) is a table of contents for the entire book, with each of its six questions answered in order by the six subsequent sections — a logical precision that rivals modern technical writing. The article analyzes each question and shows how it maps to its corresponding section, revealing Habakkuk as far more orderly and systematic than most readers have recognized. This structural insight is essential for understanding why 153, as the seventeenth triangular number, is connected to Habakkuk and to the miraculous catch of fish in John 21."),

    ("habakkuk-part-2.md",
     "Habakkuk 1:5-11 appears to describe one invading empire — the Chaldeans — but conceals five successive empires within a single prophecy: Babylon (bitter and proud), Persia (projecting justice and dignity), Greece (swift as leopards), Rome (the evening wolves), and Islam (the eagle from afar). The evening wolves capturing Jerusalem at the close of the fourth millennium precisely locates the arrival of Messiah, because Daniel promised the kingdom of God would be established during the fourth empire; the wolf at evening followed by a sunrise is Habakkuk's way of encoding the timing of Christ's birth. Each empire pioneered new means of rapid conquest, fulfilling the twin themes of bitterness and haste that the passage emphasizes seven times each. God answered Habakkuk's question about how long oppression would last by encoding the full sequence of oppressors in a single compressed oracle."),

    ("habakkuk-part-3.md",
     "Habakkuk 1:12-2:1 presents three interlocking trios of complaints about imperial cruelty, all centered on the imagery of nets, hooks, and dragnets used to catch and destroy nations as if they were helpless fish. The prophet turns the metaphor around, weaving a philosophical syllogism designed to catch God in his own logic: since God is eternal and unhurried, will He allow the wicked to empty their nets forever? A second layer of meaning is revealed: the choice between net and dragnet encodes the degree to which each of the five empires imposed cultural uniformity — monocultures like Babylon and Greece used nets of forced conformity, while more multicultural empires like Persia and Rome used dragnets of persuasion and accommodation. Jesus' reversal in John 21 — turning killing nets into life-giving nets of evangelism — is the direct answer to Habakkuk's desperate plea."),

    ("habakkuk-part-4.md",
     "Habakkuk 2:2-5 is structured as three quartets building toward a single climactic statement — 'the righteous shall live by faith' — which stands as the theological heart not only of Habakkuk but of all New Testament soteriology. God responds to the prophet's complaints with four instructions on how to communicate the vision, four assurances that it will be fulfilled, and four character portraits of the wicked (pride, treachery, greed, and oppression) — but slips in the fifth element of faith like a secret signal that the righteous will survive among these corrupting empires. The whole book forms a seven-part chiasm with this verse at its center, and that same verse sparked the Protestant Reformation when Martin Luther read it and grasped salvation by grace through faith alone. This article reveals how Paul, Luther, and Habakkuk all arrived at the same great truth hidden in the prophet's carefully layered answer."),

    ("habakkuk-part-5.md",
     "The five woes of Habakkuk 2:6-20 form a chiasm with the five civilizations identified in earlier sections, pronouncing specific divine sentences on each empire in reverse order — Ottoman Islam first, then Rome, Greece, Medo-Persia, and finally Babylon. Each woe matches the characteristic sin of its target civilization: the Ottomans were destroyed by their own debt and extravagant spending; Rome tried to build its nest in permanent security; Greece founded cities on bloodshed; Persia made neighbors drunk with wrath; and Babylon used sacred temple vessels to toast pagan idols. The prophet explicitly states that the words to follow are riddles, inviting the reader to decode the true targets behind the surface language. Connecting these woes to their fulfillments in history reveals Habakkuk as a precise prophetic document that anticipated the downfall of every major oppressor of Israel."),

    ("habakkuk-part-6.md",
     "Habakkuk 3:1-16 is the climax of the prophecy — a tightly structured war poem in which God's battle against oppressive empires is described through ten themes each repeated precisely six times, with the prophet's own sixfold physical response adding a seventh dimension. The ten themes — time, weapons, divine wrath, human fear, heaven and earth, water, glory, shaking, enemies, and the prophet's own trembling — each appear exactly six times, demonstrating intentionality that transcends poetic convention. The author tentatively identifies six passages as corresponding to six historical events: God approaching the field of battle, Persia defeating Babylon, Greece defeating Persia, Rome defeating Greece, Islam defeating Rome, and European powers defeating Islam. The final defeat of Leviathan — the ultimate beast — is acknowledged but left for a more definitive treatment in the companion article on Habakkuk's War."),

    ("habakkuk-part-7.md",
     "The final section of Habakkuk (3:17-19) lists six agricultural failures — no blossoms on the fig tree, no fruit on the vine, no olive harvest, no food from the fields, no flock in the fold, and no cattle in the stalls — each symbolizing an aspect of Israel's restoration that could not be fulfilled at Jesus' first coming. Jesus directly addressed two of these at his resurrection: he provided a shepherd (commissioning Peter in John 21) and the bread of life; but the restoration of political Israel (the fig tree) and the Levitical priesthood (the vine) had to await the fullness of time. The three seventeenth verses of Habakkuk's three chapters capture three categories of victory: rescue of the innocent, judgment of the wicked, and provision of wise leadership. The prophet's final praise — 'I will rejoice in the Lord' — offered in the face of total agricultural failure stands as one of the most remarkable acts of naked faith in all of Scripture."),

    ("habakkuk-s-war.md",
     "This article returns to Habakkuk 3:1-16 with a data-clustering approach — mapping ten sixfold themes across sixteen verses — to uncover a six-battle sequence encoding the successive defeats of Babylon by Persia, Persia by Greece, Greece by Rome, Rome by Islam, Islam by European colonial powers, and finally all enemies by God at the last day. The key methodological insight is that ignoring the surface meaning of words and searching for the underlying mathematical structure first revealed a historical pattern that the words themselves had obscured. Each empire's defeat is encoded in imagery drawn from its own cultural history: the Persian veiling of power in the Book of Esther, the Greek measurement of the earth, Rome's chariots and the sea, Islamic bows and the moon, and the European marching through the earth in fury. This approach, which the author compares to a zero-knowledge proof in cryptography, validated the overall analytical method used throughout the Habakkuk series."),

    ("hannah-s-song.md",
     "Hannah, mother of the prophet Samuel, is identified as possibly the wisest woman in the Bible because her ten-verse prayer in 1 Samuel 2 encodes a complete prophetic framework that anticipates both Solomon's Growth Pattern and the existence of the seven pillars of wisdom — centuries before either was written. Her prayer's seven reversals of fortune precisely match the seven phases of the Growth Pattern, and her phrase 'the barren has borne seven' names the number of pillars while 'the pillars of the earth are the Lord's' names their essence. The article explores how Hannah's sacrifice — giving up her firstborn Samuel to serve God — connects to priestly ordination rituals and thereby to the question of women's roles in the church. Hannah's prophetic clock, embedded in her prayer, maps seven 480-year eras of history from the dedication of Solomon's temple, demonstrating that this overlooked prophetess was one of the most structurally profound voices in all of Scripture."),

    ("harvest-pattern.md",
     "The Harvest Pattern, derived from Jesus' parables of agricultural growth in Matthew, is a seven-phase framework for understanding how God brings barren souls into spiritual fruitfulness — introduced through the author's personal story of how it operated in his own life decades before he recognized it. The pattern's phases (plowing, planting, watering, pruning, harvesting, and more) can be traced backward through any spiritual breakthrough to reveal God's continuous care stretched across months and years. The article argues that memorizing and meditating on Scripture is more powerful than most Christians believe, tracing how the author's memorization of Galatians 2:20-21 led to deliverance from the fear of death and how Habakkuk 3:17-19 sustained him through depression to graduation from MIT. As the practical counterpart to the Growth Pattern, the Harvest Pattern governs not the normal course of life but the miraculous interventions by which God transforms barren souls into fruitful ones."),

    ("heavenly-treasures.md",
     "Jesus commands his followers to lay up treasures in heaven but never lists what they are — this article fills that gap with a twelve-item inventory derived from decades of searching Scripture, starting with the Fear of the Lord and culminating in the Glory of God. The list is organized into a four-category framework — Being (eternal life), Establishing (family, work, authority), Nurturing (love, wisdom, courage), and Flourishing (freedom, happiness, joy) — each grounded in specific biblical texts. The article traces back to the author's memorization of the Sermon on the Mount in his early Christian life and the question it raised that launched over a decade of searching: if Jesus says to treasure things in heaven, what exactly are those things? The answer is not abstract but deeply practical, defining the goals that should orient every Christian's investment of time, energy, and devotion."),

    ("home.md",
     "This is the welcome page for the entire website, introducing Lady Wisdom's House as the organizing metaphor for a comprehensive biblical wisdom system built around three interlocking patterns: Solomon's Growth Pattern from Ecclesiastes, Jesus' Harvest Pattern from Matthew, and Moses' Law Pattern from Exodus. The site promises original research into seven core wisdom books — Psalms, Job, Proverbs, Song of Songs, Ecclesiastes, Matthew, and Revelation — through the lens of a new eschatological system called Fractal Historicism, which treats the Growth Pattern as the mainspring of all biblical prophecy. Beyond personal spiritual application, these patterns provide a prophetic map of history that enables readers to understand the timing of God's past and future judgments with unprecedented precision. The website constitutes a guided tour of Lady Wisdom's house, room by room, for anyone who wants to understand both how to grow to spiritual maturity and how God is guiding history toward its appointed end."),

    ("identification.md",
     "This article — part of the women's ordination series — explores how the Seven Pillars of Wisdom connect to women's voices through figures like Lady Wisdom, Hannah, the Wife of Noble Character, and the Bride of Song of Songs, building a biblical case for women's full participation in church life. Hannah's prayer is decoded to show seven reversals of fortune matching the seven phases of the Growth Pattern, and her phrase 'the barren has borne seven' is revealed as the earliest prophecy of the seven pillars themselves. The stability phase of the Growth Pattern (1 to 480 AD) is shown to coincide precisely with the historical period when women were progressively removed from church leadership roles — suggesting this was a biblically foretold season of confinement rather than the permanent divine intention. By grounding the discussion in the structural wisdom patterns of the Bible itself, the article argues that Scripture provides its own framework for understanding when and why restrictions on women's ministry were imposed and why they should be lifted."),

    ("industrial-revolution.md",
     "This wide-ranging article demonstrates that the Fifth Trumpet judgment of Revelation 9 — a 153-year plague of locusts from 1765 to 1918 AD — corresponds in precise detail to the Industrial Revolution and the era of Christian colonial empires led by queens, especially Britain's Queen Victoria. The locusts with women's hair, iron breastplates, lion's teeth, and scorpion-sting tails encode the queens' gender, their empires' Roman heritage, Britain's lion symbol, and the poison gas and machine guns of World War I. Beyond Revelation 9, the article catalogs over forty converging prophetic clocks from Ecclesiastes, Job, Matthew, the Psalms, and the Book of Revelation that all point to the same 1765-1918 era, including the Church of Philadelphia, Solomon's sundial, and the Parable of the Ten Virgins. The article amounts to a tour de force of convergent prophetic evidence for Fractal Historicism, treating the Industrial Revolution and its devastating wars as the fulfillment of God's judgment on both the world's pagan empires and Christendom itself."),

    ("job-course-of-empires.md",
     "This article reveals a thirteen-empire prophetic clock hidden in the Book of Job, surpassing in scope the five-empire clock of Habakkuk and the seven-empire clock of Revelation, by matching each speech in Job to a different world civilization and using the moral character of the speaker as a predictor of that era's moral tone. Dark speeches by Satan, Eliphaz, Bildad, and Zophar correspond to dark historical eras, while Job's own speeches and Elihu's correspond to better times — a speaker clock in which the dramatic texture of the book doubles as a chronological map of history. The article cross-references this Empire Clock with Job's Generational Clock (in which each chapter corresponds to a 119-year generation) to show that Job contains two independent yet overlapping prophetic systems. By including an anti-kingdom (the void) and God's eternal kingdom among its thirteen, Job provides the most complete structural blueprint for biblical prophecy about world history yet identified."),

    ("job-description-for-a-savior.md",
     "By asking what sustained Job's hope in each moment of despair, the author discovered nine sequential prophecies in Job's speeches that describe the life of Christ in chronological order — from his pre-incarnate glory to his birth, healing ministry, crucifixion, resurrection, and second coming — without Job knowing he was composing a divine job description. These nine requirements for a savior, scattered across Job's speeches as complaints and longings, are shown to have been fulfilled exclusively by Jesus of Nazareth, making the Book of Job an extended Messianic prophecy hidden beneath layers of suffering. Two obstacles block readers from seeing this: the intellectual labor of systematic biblical study and the emotional barrier erected by Job's suffering, which mirrors readers' own unresolved pain and causes them to recoil from the text. Once both head and heart have been prepared by God's grace, the article argues, the prophetic system in Job becomes not only visible but inescapable."),

    ("job-s-anti-jubilee-clock-defined.md",
     "This article presents a prophetic clock running from Abraham to Jesus hidden in the Book of Job, structured around the Year of Jubilee — the 50-year cycle of debt cancellation, slave release, and land restoration commanded in Leviticus 25. The clock is called anti-Jubilee because it traces the accumulation of oppression and injustice that made Christ's redemption necessary, running inverse to the cycles of liberation. The author introduces the discovery through his personal experience of a literal Jubilee year in 2022: his father's death freed the family from decades of debt, while a near-fatal fall through frozen pond ice — and his miraculous calm during twenty-five minutes in frigid water — demonstrated the life-preserving power of years spent studying biblical wisdom. Like other prophetic clocks, this one contains a built-in riddle that specifies the length of each period, proving systematic intentionality in Job's text and validating the broader methodology of the website."),

    ("lady-wisdom-s-house.md",
     "This article explores the recurring biblical metaphor of building a house — from Solomon's temple to Jesus' parable of the wise and foolish builders — and argues that these uses are connected to a single overarching concept: Lady Wisdom's House, the organizing framework for all biblical wisdom. Just as the labeled tabs of a paper model must be inserted into matching slots to produce the final structure, the riddles scattered through the wisdom books (like the Seven Spirits of God and the Voices of the Seven Thunders) are structural connectors that link seemingly disparate passages into one coherent edifice. Understanding the architecture of this house, the author argues, transforms scattered biblical teachings into a unified system with practical implications for spiritual growth, church history, and eschatology. The article surveys several such connective riddles and shows how each, once decoded, opens up a new room in Lady Wisdom's house."),

    ("lady-wisdom.md",
     "This article introduces Lady Wisdom — the personified Wisdom of Proverbs — as a living, knowable figure whose four appearances in Proverbs (chapters 1, 3, 8, and 9) reveal a progressively deepening relationship, from public street preacher to intimate dinner hostess. The author approaches her the way one approaches a favorite author: through her books, then her biography, then a pilgrimage to her house — and confesses that it took decades of study before the depth of her wisdom became apparent. Her résumé in Proverbs 8, where she claims to have been present at the creation of the world and to have been the master craftsman at God's side, is explored as the strongest biblical evidence for her identity as either the pre-incarnate Christ or the Holy Spirit. The article is a personal and scholarly invitation to begin the lifelong journey of getting to know Lady Wisdom, whose house the entire website is devoted to exploring."),

    ("law-pattern.md",
     "The Law Pattern of Moses — encoded in the Ten Commandments — is revealed as the true foundation of Lady Wisdom's House and the matrix into which both the Growth Pattern of Solomon and the Harvest Pattern of Jesus perfectly fit. The first tablet of commandments, governing love of God, matches the Harvest Pattern point for point; the second tablet, governing love of neighbor, matches the Growth Pattern — confirming that the commandments together bridge eternity and time, spirit and matter. The Ten Commandments function as a structural template throughout the Bible, sometimes organizing material into ten parts and sometimes into fourteen (when each commandment is parsed into its component imperative statements), as seen in Hannah's prayer, the letters of 1 and 2 Timothy, and the entire Gospel of Matthew. This article introduces the two sub-articles that work out the implications of the Law Pattern in detail: Which Ten Commandments? and Matthew and the Law of Christ."),

    ("lifespan-of-solomon.md",
     "This article tackles the chronological puzzle of determining Solomon's birth year — information not directly stated in Scripture but necessary to solve a riddle embedded in Ecclesiastes about a man who lives 'a thousand years twice over.' Drawing on the genealogical analysis of Pastor D. Thornton and supplementing it with reasoning from 2 Samuel and 1 Chronicles, the author arrives at a best estimate of sixty-three years for Solomon's lifespan. The riddle-solving method — identifying a number embedded in poetic text, then using known historical anchors (the temple dedication in 960 BC) to calculate its prophetic implications — is a microcosm of the broader methodology used throughout the website. Without knowing Solomon's age, the prophetic calendar hidden in Ecclesiastes cannot be unlocked, making this chronological detective work a necessary foundation for the entire system of Fractal Historicism."),

    ("matthew-and-the-law-of-christ.md",
     "The Gospel of Matthew is shown to be structured according to the fourteen imperative statements of the Ten Commandments, with each pair of chapters providing commentary on one commandment as reinterpreted by Jesus under the new covenant — making concrete what Paul called 'the Law of Christ.' The discovery was made when the author noticed that the center chapters of Matthew call Jesus the Lord of the Sabbath and discuss the fifth commandment, landing precisely at the center of the fourteen imperatives. The structure functions as a decoder ring for Pauline theology about law and grace: the Law of Christ is not a vague rhetorical concept but a specific content visible in Matthew's architecture. Together with its conformity to the Growth Pattern and the Harvest Pattern, this Law Pattern conformity makes Matthew the most structurally complex and prophetically rich book in the New Testament."),
]

count = 0
for source, synopsis in updates:
    old = f"  source: {source}\n  synopsis: No synopsis yet"
    new = f"  source: {source}\n  synopsis: {synopsis}"
    if old in content:
        content = content.replace(old, new, 1)
        count += 1
    else:
        print(f"WARNING: could not find placeholder for {source}")

with open('/Users/Paul.Chernoch/Documents/GitHub/paulchernoch/source/synopsis.yaml', 'w') as f:
    f.write(content)

print(f"Updated {count} synopses.")
remaining = content.count('No synopsis yet')
print(f"Remaining placeholders: {remaining}")
