import re

with open('source/synopsis.yaml', 'r') as f:
    content = f.read()

synopses = {
    "the-end-times.md": "This article introduces Fractal Historicism — the original system of eschatology developed by the author and explored throughout the website — which applies the Growth and Harvest Patterns of biblical prophecy like fractals at multiple timescales, from the span of all history to the shorter spans of Israel's and the Church's development. The system stands in the tradition of classical Historicism (favored by Luther, Calvin, Wesley, and other Reformers), which matches biblical prophecy to actual historical events, but departs from earlier Historicism by not identifying the Pope as the Antichrist and by recognizing that the same prophetic patterns repeat at different scales. The article surveys all the end-times topics covered on the website — the seven cycles of judgment, the millennial kingdom, the four horsemen, the industrial-revolution era of the fifth trumpet, the coming fifth seal, and the mystery of the seven thunders. A diagram comparing Fractal Historicism to competing eschatological systems (Preterism, Futurism, and Idealism) orients the reader to how this system relates to other common approaches.",

    "the-fifth-seal.md": "This article argues that the coming opening of the Fifth Seal of Revelation will trigger a global persecution of Christians that separates the faithful from the unbelieving world, plunging non-Christians into a worldwide plague of darkness analogous to Egypt's ninth plague. Five converging prophetic themes — Solomon's time to hate, the fifth seal, the Exodus plague of darkness, the ninth commandment against lying, and the tenth commandment against covetousness — all point to the same near-future era, as established by the prophetic clocks analyzed in the author's books. The unexpected silver lining is that even as the world darkens, God will be opening the minds of the faithful to see marvelous new truths hidden in Ecclesiastes (illuminated by the Spirit of Might) and eventually in Matthew. The article carefully distinguishes speculation about how the prophecy will be fulfilled from the confident claim that the biblical clocks have already identified the era in which it will occur.",

    "the-journey-pattern.md": "Matthew's genealogy of Jesus deliberately counts 42 generations — not 41 — from Abraham to Jesus by counting David twice, and this article argues that the number 42 is not a scribal error but a deliberate clue pointing to the Journey Pattern, the biblical framework governing the long human journey from expulsion from Eden back to the New Jerusalem. The number 42 connects to the 42 stations of Israel's wilderness journey in Numbers 33 and to the 42-month tribulation periods in Revelation, establishing 42 as the number of the journey itself. The article explores how God measures time in generations of people rather than abstract years, and how Matthew's genealogy encodes this framework as a table of contents for all of redemptive history. The Journey Pattern complements the Growth and Harvest Patterns by providing the overarching narrative arc — the long road back to Paradise — within which those other patterns operate.",

    "the-meaning-of-the-beasts-of-job.md": "This article, the second part of a two-chapter analysis of Job as a prophetic empire clock, reveals that God judged each empire identified in Job for breaking a specific commandment — and that these judgments proceed in the same sequence as the commandments listed in Exodus 20. The friends' speeches in Job, condemned by God as wrong about Job personally, are shown to function as 'negative theology': inverted, they reveal truths about oppressive civilizations and their eventual divine punishment. A key structural insight is that Job's descent-to-the-grave passage (Job 17) appears immediately before Job's resurrection cry ('I know that my Redeemer lives!' in Job 19), mirroring the historical sequence of Babylonian exile followed by Persian restoration under Cyrus — showing that the history of empires is intimately woven into the plan of salvation. The article builds on 'Job: The Course of Empires' and together they form a complete two-chapter portrait of Job as the Bible's most comprehensive prophetic framework for world history.",

    "the-millennial-kingdom.md": "This article argues from multiple converging prophetic clocks that the Millennial Kingdom of Christ began in 380 AD — when the Edict of Thessalonica made Christianity the official state religion of Rome, effectively binding Satan's power to openly deceive the nations — and ended approximately 1,000 years later in 1380 AD, when Satan was released. The first resurrection of Revelation 20 is interpreted as a non-visible, heavenly event: martyrs reigning with Christ in heaven, not a physical raising of bodies on earth — a reading that avoids the chronological impossibility of a literal future millennium extending history beyond 7,000 years. The article works backwards from the present and forwards from the Creation, cross-referencing multiple Fractal Historicism prophetic clocks to narrow down the millennium's dates. Interpreting the text through the lens of what Satan was doing — when was he most constrained, when most unleashed — proved to be the unexpected analytical key that unlocked the passage.",

    "the-motherhood-pattern.md": "This article discovers a Motherhood Pattern encoded throughout Scripture, showing that God uses the female experience — birth, puberty, marriage, conception, childbirth, and death — as a template for structuring both history and prophecy. The article matches six major civilizations to the stages of a woman's life, showing that each civilization lived through analogous phases, though only five delivered 'babies' into the stream of history. A second major section surveys the spirit-filled women of the Old Testament — from Sarah to Miriam to Rahab — and demonstrates that each exemplified a particular Spirit of God from Isaiah 11, providing a female-centered witness to the seven spirits. A final section addresses practical questions: what the Bible teaches about children's education, the appropriate age for marriage, and how Job's story functions as a parable of women's suffering and ultimate vindication.",

    "the-righteous-fall-seven-times.md": "Proverbs 24:16 — 'for the righteous falls seven times and rises again' — was the verse that inspired the author to study Job as a model of resilience after personal crisis, and this article explores how that verse unlocked both the structure of Job and deeper truths about how God trains people to endure suffering. The article introduces the concept of Emotional Riddles — biblical passages that repel the reader with apparent sexism, racism, or divine unfairness before yielding unexpected wisdom to those who wrestle with them long enough. Drawing parallels between Proverbs 24 (matched to Ecclesiastes 3's 'time to tear'), Job 5:19 ('from six calamities he will rescue you; in seven no harm will touch you'), and the author's own experience of parental grief, it shows that seven is not merely a number but the shape of perseverance itself. The article sets the stage for deeper study of Job as the Bible's supreme portrait of resilient faith.",

    "theme-of-books.md": "This article examines the theme of books running through the Seven Pillars of Wisdom — Psalms, Job, Proverbs, Song of Songs, Ecclesiastes, Matthew, and Revelation — as part of the larger project of demonstrating that these seven books form a coherent, intentionally designed unit. Beginning from Solomon's two bronze temple pillars (Jachin meaning 'he establishes' and Boaz meaning 'in him is strength'), it demonstrates that pillars have a dual nature: strength for navigating today and establishment across time, mapping respectively to the Harvest Pattern and the Growth Pattern. The article explains why the Pentateuch (especially Exodus) serves as the floor of Lady Wisdom's house rather than one of its pillars, grounding the entire structure in the Law and in the lapis lazuli pavement beneath God's feet. An analysis of how each pillar book references and honors the Books of Moses reveals the deep structural unity woven into the entire biblical canon.",

    "theme-of-pillars.md": "This article traces the recurring theme of pillars through each of the Seven Pillars of Wisdom, demonstrating that the seven books form a unified architectural whole in which each pillar book actually discusses pillars as a metaphor for the qualities of wisdom. Beginning with Proverbs (which names and numbers the seven pillars in chapter 9 and lists all seven Spirits of God in chapter 8) and moving through Psalms (including Psalms 75, 99, and 144 on strength and establishment), the article builds the case that both principal attributes of pillars — strength for today and establishment across time — appear consistently across all seven books. The connections between Psalm 144's prayer for sons strong as plants and daughters beautiful as corner pillars and Revelation's promise to the church of Philadelphia show how the pillar imagery threads from the psalms all the way to the end of the Bible. This article is part of 'Appendix H: Clues to the Seven Pillars,' which assembles the cumulative case that the seven books were designed to function as a unity.",

    "theme-of-songs.md": "This article traces the recurring theme of songs and singing through the Seven Pillars of Wisdom, finding that the pillar books are full of song as both sorrow and celebration — and that the mark of wisdom is knowing which kind of song the present moment calls for, or whether to remain silent. A striking observation is that Jesus quoted the Psalms more than any other Old Testament book, indicating that the Psalms occupy the pinnacle of the worship tradition; through worship we both come to understand God and discover that God understands us, making Psalms the home of the Spirit of Understanding. The article traces songs of darkness and dawn, harvest and exile, across Psalms, Job, Song of Songs, and Revelation, weaving them into a single argument that song is the primary language of wisdom. This is one of seven theme articles that together constitute the cumulative proof that the Seven Pillars of Wisdom are a deliberate, unified biblical set.",

    "theme-of-spirits.md": "This article examines how each of the Seven Pillars of Wisdom exemplifies one of the Seven Spirits of God named in Isaiah 11:2 — the Spirit of the Lord, Wisdom, Understanding, Counsel, Might, Knowledge, and the Fear of the Lord — while all seven spirits appear in every book. The analysis shows that the Psalms, with 'the LORD' appearing 717 times (and 24 times in Psalm 119 alone), are unmistakably the book of the Spirit of Lordship; Job's great hymn to wisdom in chapter 28 makes it the book of the Spirit of Wisdom; and each remaining pillar book is matched to one spirit by equally compelling textual evidence. The article demonstrates that Jesus is specially associated with both the Spirit of Wisdom and the Spirit of Knowledge — a theological insight with deep implications for Christology. This is one of seven theme articles that together constitute the cumulative proof that the Seven Pillars of Wisdom are a deliberate, unified biblical set.",

    "theme-of-swords.md": "This article traces the theme of swords through the Seven Pillars of Wisdom, finding in sword imagery a thread connecting the Psalms' prophetic cries (including Psalm 22, Jesus' only Bible quotation from the cross) to Job's portrayal of divine judgment to the two-edged sword of the risen Christ in Revelation. In Psalms, seven of the nineteen sword occurrences use the sword as an analogy for speech, and seven are explicitly prophetic; in Job, the sword moves from literal slaughter in the opening chapter to the metaphysical limit at the end — no sword can subdue Leviathan, only eternal destruction. A personal reflection on waking in the night consumed with rage, tempted to wield God's own sword against the wicked, illustrates how even the most even-tempered reader is drawn into Job's more wrathful moods. This is one of seven theme articles assembling the cumulative proof that the Seven Pillars of Wisdom form a deliberate, unified biblical unit.",

    "theme-of-thunders.md": "This article traces the theme of thunders through the Seven Pillars of Wisdom and their connections to Exodus, revealing how the seven thunders of Revelation are foreshadowed in Psalms, Job, and the Sinai theophany — and how these cross-connections anchor the pillars to the Mosaic foundation. A sweeping cross-reference chart connects over a dozen passage pairs spanning Psalms, Revelation, Job, and Exodus, showing that the same images (thunder, lightning, fire, sea monsters, the lamb) appear across all of these books in deliberate parallel. Jeremiah's seven analogies for God speaking — roar, thunder, roar mightily, shout, shout, and bring charges — are shown to evoke the seven thunders, while also connecting to the theme of swords. The article culminates with a return to the rainbow of Revelation 10, which ties together pillars, thunders, spirits, and the theme of books in a single convergent vision.",

    "theme-of-treasures.md": "This article examines the theme of treasure running through the Seven Pillars of Wisdom, arguing that the tension between true and false treasure is the organizing metaphor for all genuine worship: treasuring what God treasures is worship, while treasuring the impermanent or unclean is idolatry. Beginning with Psalm 115's devastating portrait of idols — made of silver and gold but unable to see, hear, smell, or speak — it connects treasure language to all the healing miracles of Jesus (who undid precisely the disabilities the psalm describes) and notes that 'the LORD' appears twelve times in that one psalm, linking treasure and lordship. The analysis proceeds through Job, Proverbs, Song of Songs, Ecclesiastes, Matthew, and Revelation, tracing the true-versus-false-treasure dialectic in each. As a capstone article in the series, it also derives insights from all seven themes together and explains why Jesus is specially associated with both the Spirit of Wisdom and the Spirit of Knowledge.",

    "there-is-a-season.md": "This article explores the 28 times of Ecclesiastes 3 — 'A time to be born, and a time to die; a time to plant, and a time to pluck up...' — discovering in them the Growth Pattern, a prophetic framework that governs not only the life of an individual but the arc of civilization and world history. Originally published as a chapter in *Peace, like Solomon Never Knew*, the article connects the 28 times to the Five Factor Model of personality (OCEAN), showing that each phase of growth corresponds to a personality trait being formed or tested. The paired contrasts of the poem (wet vs. dry season, planting vs. harvesting, tearing vs. sewing) are decoded as a table of contents for all of Ecclesiastes, with the recurring phrase 'under the sun' serving as a structural marker dividing the book into 28 sections. The realization that God measures human history in the same rhythms as a single human life gives the poem a grandeur that far exceeds its brevity.",

    "timeless.md": "This article surveys the 'empire clocks' embedded in Daniel, Revelation, and other prophetic books, explaining how they reveal the sequence and character of the major world empires without providing precise dates — making them 'timeless' clocks, qualitative rather than quantitative. The article introduces Ellis Skolfield's rule for identifying which empires belong to the master sequence: only those that captured Jerusalem qualify, a test that filters the many candidates down to the handful Scripture emphasizes. Using the analogy of dendrochronology (matching tree rings to reconstruct ancient climates), the article shows how overlapping prophecies from different books can be aligned to build a composite picture of the full sweep of empire from Babylon to the final kingdom. The article is drawn from the chapter 'Timeless?' in *Peace, like Solomon Never Knew*.",

    "to-number-our-days.md": "Psalm 90:12 asks God to 'teach us to number our days, that we may gain a heart of wisdom,' and this article takes that request seriously — establishing ten rules for interpreting numbers in Scripture without falling into the traps of numerology or wishful pattern-matching. The author, an MIT-trained physicist, brings scientific skepticism to biblical number interpretation: he debunks the popular claim that the word 'lamb' appears 28 times in the Bible, demonstrates the complexity of counting across translations, and insists that numbers should suggest associations rather than prove them. The article then introduces the key numbers that recur throughout the website's prophetic analysis — 7, 10, 12, 14, 28, 42, and others — situating them within their biblical contexts and explaining the rules that govern valid interpretation. It is drawn from the chapter 'To Number our Days' in *Peace, like Solomon Never Knew* and serves as an essential methodological preface to all the prophetic clock analysis on the website.",

    "twice-a-thousand-years.md": "This article tells the story of how the author discovered and decoded the master riddle of Ecclesiastes — a riddle in chapter 6 about a man who would rather not live 'twice a thousand years' in joyless futility — which turned out to be the key that unlocked the entire prophetic structure of the book. The discovery process spanned a decade and proceeded in nine steps: decoding the 28 times as stages of human growth, recognizing 'under the sun' as structural punctuation dividing the book into 28 sections, identifying the riddle's position in time, discovering that the same pattern operates fractally at multiple scales (one life, modern Israel, Judeo-Christian civilization, all of humanity), and connecting the 28 times to the Seven Pillars of Wisdom. The article presents a summary of the Growth Pattern's derivation that is both intellectually rigorous and personally moving, drawn from *Peace, like Solomon Never Knew* and *Plague, Precept, Prophet, Peace*. Like Omar Khayyam's Rubaiyat, it is about the seven gates one must pass through to sit upon wisdom's throne.",

    "two-patterns-in-history.md": "This article traces the Journey Pattern — the 42-generation structure spanning all of human history from Adam's expulsion from Eden to Christ's return — by examining key events at symmetric pairs of generations and showing that God has structured all of history as a chiasm, a grand poetic palindrome. Generation 1 (Eden's expulsion) is matched by generation 42 (Christ's return); generation 7 (Abraham's near-sacrifice of Isaac on Moriah) is matched by generation 35 (the Ottoman capture of Jerusalem); generation 14 (David's capture of Jerusalem) is matched by generation 28 — and so on, with temple building, breaking, and rebuilding as the central recurring theme. The symmetry reveals that Jerusalem is the axis around which all 42 generations pivot, and that history's apparent chaos resolves into a majestic pattern when viewed at the scale God intended. The article demonstrates that the two great patterns of history — the Growth Pattern and the Journey Pattern — together explain both the inner development and the outer narrative of all civilization.",

    "types-of-clock.md": "This article catalogs the major types of prophetic clock found in the Bible, derived from a careful reading of Ecclesiastes 1, where the author discovered that Solomon had encoded a taxonomy of prophetic patterns in the very opening chapter of his wisdom book. The types include the Cosmic Chiasm (history proceeding in one sequence then repeating in reverse — the 'last in, first out' pattern), plus four others drawn from Ecclesiastes 1's imagery of the sun, wind, rivers, and the deep. A key methodological point: the author refused to proceed without biblical warrant for the very idea that such patterns exist, prayed for confirmation, and returned to the text — which then yielded its secrets. The article is drawn from the chapter 'Solomon's Clocks: Ecclesiastes 1' in *Peace, like Solomon Never Knew* and provides the theoretical foundation for all the prophetic clock analysis throughout the website.",

    "vineyard-parable.md": "Jesus' Parable of the Workers in the Vineyard (Matthew 20:1-16) — in which workers hired at different hours of the day all receive the same pay — turns out to encode a detailed prophetic timeline of the five major waves of Christian missionary activity across history, with each hour of the workday corresponding to a distinct era of missions. The article, drawn from 'A Minute Look at Matthew' in *Peace, like Solomon Never Knew*, is part of a larger analysis showing that Matthew contains at least seventeen instances of the Harvest Pattern and that several parables function as miniature prophetic clocks. When read alongside the Parable of the Talents (church growth), the Parable of the Ten Virgins (role of women), Psalm 107 (geographic direction), and the Parable of the Wedding Feast (condition of missionaries), the Vineyard Parable completes a five-way system that gives a remarkably precise picture of the entire history of Christian missions. The discovery that even the hour of each group's hiring encodes a specific historical date makes this one of the most precisely prophetic parables in Matthew.",

    "wedding-parable.md": "Jesus' Parable of the Wedding Feast (Matthew 22:1-10) — in which a king's servants invite guests to his son's wedding, are rejected and killed, and the feast is filled from the roads instead — is decoded as a prophetic history of the fate of Christian missionaries across five major eras, answering the question: what happened to the men and women who left everything to carry the Gospel to the world? The article situates the Parable of the Wedding Feast within a five-parable system in which each parable illuminates a different aspect of the church's missionary task: timeline, growth plan, role of women, geographic direction, and the condition of the missionaries themselves. The disturbing detail — that the king 'sent his troops and destroyed those murderers and burned their city' — is shown to be a literal prophecy about the Roman destruction of Jerusalem in 70 AD, marking the end of the first missionary era. Together, the five parables form one of the most detailed prophetic pictures of church history anywhere in the New Testament.",

    "which-ten-commandments.md": "This article defines the Law Pattern — the structural framework underlying the Ten Commandments — and addresses a surprising complication: Jews, Catholics, and Orthodox/Reformed Christians parse the commandments into ten in three different ways, and only one of those ways (the Orthodox/Reformed division) preserves the prophetic structure that matches the Ten Plagues of Egypt to cycles of divine judgment against successive civilizations. The article examines Augustine's division (which combines the first two commandments and splits coveting into two), the Jewish division (which treats the preamble as the first commandment), and the Orthodox/Reformed division, showing why the prophetic pattern only works with the last of the three. The Law Pattern reveals that the commandments are structured according to the Trinity and that the Word of God is both divine and human, eternal and living in time. In its original context this chapter followed analysis of how God judged Persia, Greece, and Rome for breaking specific commandments — making the theological stakes of the parsing question concrete and urgent.",

    "yoke-of-jesus.md": "This article argues that when Jesus says 'Take my yoke upon you' in Matthew 11:29, the yoke he describes is not merely his teaching or his law but specifically the Holy Spirit — and that this identification unlocks the entire flow of Matthew 11-12, which moves from Jesus' invitation to rest, through healings on the Sabbath, through controversy about Sabbath observance, to the climactic warning against blaspheming the Holy Spirit. The article demonstrates the technique of 'deconstructing the Holy Spirit' — showing how both Matthew 11 and Ephesians 1:15-23 enumerate all seven Spirits of God from Isaiah 11 in sequence without naming the Spirit explicitly, a technique that invites careful readers to reconstruct the Spirit's presence from the surrounding details. All seven spirits are identified in the Ephesians passage with detailed textual support, proving the technique is deliberate and that Jesus' 'yoke' passage centers on the Spirit of Might, which brings rest from heavy burdens. The article is an excerpt from an upcoming book on the many ways to speak with God.",
}

updated = 0
for source_file, synopsis_text in synopses.items():
    old = f"  source: {source_file}\n  synopsis: No synopsis yet"
    new = f"  source: {source_file}\n  synopsis: {synopsis_text}"
    if old in content:
        content = content.replace(old, new)
        updated += 1

with open('source/synopsis.yaml', 'w') as f:
    f.write(content)

remaining = content.count("synopsis: No synopsis yet")
print(f"Updated {updated} synopses. Remaining placeholders: {remaining}")
