import re

with open('/Users/Paul.Chernoch/Documents/GitHub/paulchernoch/source/synopsis.yaml', 'r') as f:
    content = f.read()

updates = [
    ("most-important-questions.md",
     "This article identifies twelve meta-questions whose answers, when discovered, transform the seeker — questions that God uses to guide people forward rather than simply handing them answers. The twelve questions are self-authenticating: only after finding an answer that changed you, opened your eyes, or set you free do you recognize it was the right question to ask. The author traces his own journey from memorizing the Sermon on the Mount and discovering the Golden Rule, to a decade-long search for heavenly treasures, to further questions about spiritual resilience and the path to peace — each question arising out of the unresolved residue left by the previous answer. The twelve questions serve as an organizing framework for the entire website, helping visitors identify which articles speak most directly to their own season of seeking."),

    ("numerology.md",
     "This article defends the use of numbers in biblical interpretation against modern scholarly skepticism, arguing that the Bible contains a structured numerological vocabulary that careful study can decode without falling into the speculative errors of the past. The author distinguishes seven sources of biblical numbers — explicit counts, collection sizes, word frequencies, math puzzles, structural elements, numerical sequences, and gematria — and proposes a WHERE CLAUSE principle: numbers must always be confirmed by independent textual correspondences before being used to support an interpretation. Evidence is presented that the chapter and verse divisions of Job, 1 and 2 Timothy, Matthew, and the Psalms were not arbitrary but were divinely guided to communicate prophetic information. The article concludes by noting that careful numerical analysis may be the only key capable of unlocking three of the Bible's greatest unsolved mysteries, including the secret message of the Seven Thunders in Revelation 10."),

    ("pauls-discipleship-program.md",
     "Paul's first seven letters — Romans, 1 and 2 Corinthians, Galatians, Ephesians, Philippians, and Colossians — are revealed to form a complete discipleship curriculum when read in canonical order, with each letter addressing one of Solomon's seven phases of spiritual growth in sequence. The discovery came to the author while lying sick on a couch: without Bible or notepad, the structural correspondence suddenly became clear — Paul's letters follow exactly the course syllabus that Solomon laid out in the twenty-eight times of Ecclesiastes 3. Because Solomon's Growth Pattern is complete (he missed no phases), and because Paul's letters match every phase, Paul's program for sanctification is equally complete and fully sufficient for bringing any believer from new-convert insecurity to mature, battle-tested faithfulness. The article introduces each letter and its corresponding growth phase, providing a practical road map for the whole journey of Christian discipleship."),

    ("peace-book.md",
     "This page describes and provides the table of contents for the author's first major theological book, *Peace, like Solomon Never Knew*, which is the primary source for much of the material on this website. The book's central discovery is the Growth Pattern of Solomon, extracted from the twenty-eight times of Ecclesiastes 3 and shown to govern both the stages of individual human life and the flow of all history as a prophetic clock. A maze based on Solomon's twenty-eight times appears as a playful introduction, reflecting the book's thesis that wisdom is found by following a prescribed path through life's seasons. Readers who want the detailed scholarly argument behind the website's prophetic and discipleship frameworks will find it here, across chapters covering Ecclesiastes, the Psalms, Job, Daniel, Matthew, and Revelation."),

    ("plague-book.md",
     "This page describes and provides the table of contents for the author's second major theological book, *Plague, Precept, Prophet, Peace*, which expands the prophetic framework of the first by adding Moses' Law Pattern as the foundation beneath the Growth and Harvest Patterns. The book traces the structural correspondence of the Ten Commandments throughout the Bible — in the Psalms, Job, Matthew, Timothy, and Exodus — and shows how the plagues of Egypt and the commandments together form a matrix into which all of God's historical judgments can be mapped. A key discovery is Job's Anti-Jubilee Clock, a prophetic timeline running from Abraham to Jesus hidden in the Book of Job. The preface reveals that the book was delayed a year because God gave the author a personal Jubilee — including a near-fatal fall through ice — that provided the experiential key needed to unlock the text's teaching about the Year of Jubilee."),

    ("prophetic-clocks.md",
     "This article introduces the concept of a prophetic clock — a regular, systematic, chronological arrangement of prophecies in the Bible that covers all of history from beginning to end — and explains why God would encode such a clock in riddles rather than in plain language. Drawing on Amos 3:7 ('the Lord does nothing without revealing his secret to the prophets'), the author argues that since the biblical canon is closed, it must already contain detailed prophecies of everything God has done and will do; the challenge is to decode them. The ideal prophetic clock would be regular as a timepiece, chronological, and progressing in even intervals — and the author argues that Solomon's Growth Pattern meets all these criteria when applied at the scale of world history. The article establishes the philosophical and hermeneutical foundation for all the specific prophetic clocks explored throughout the website."),

    ("proverbs-1-to-3.md",
     "The first three chapters of Proverbs are shown to correspond to the first three millennia of history (4020-1020 BC), each chapter matching one member of the Trinity and one season of the year — a retrospective prelude before the twenty-eight forward-looking chapters that follow. Beginning with chapter 4, the remaining chapters of Proverbs follow Solomon's Growth Pattern, each covering 120 years of history from the dedication of the temple in 960 BC, making Proverbs a prophetic timeline preserved through Hezekiah's careful editorial work. This structure transforms Proverbs from a loose anthology of wisdom sayings into a sweeping prophetic narrative about the long summer of human history, building toward a final harvest. The introductory chapters reveal a failed harvest in Eden followed by three millennia of preparation — Autumn (Creation to Noah), Winter (Noah to Abraham), and Spring (Abraham to Solomon) — before the Summer of the age of the temple begins."),

    ("proverbs-20-to-29.md",
     "Proverbs chapters 20 through 29 are analyzed as a section of the prophetic clock running through the book, with each chapter matching one of Solomon's twenty-eight times and covering a 120-year era of history from roughly 960 AD to 2160 AD. Each chapter's wisdom sayings illuminate the characteristic challenge of its corresponding life phase and historical period — from searching (chapter 20, covering 960-1080 AD, the age of the First Crusade) to the coming era of war (chapters 28-29). The prophetic connections are grounded in the text itself: specific proverbs about kings, enemies, and divine judgment are matched to events in their corresponding centuries, demonstrating that the sayings were deliberately arranged to tell history in code. This section of Proverbs is a testament to the extraordinary prophetic and editorial work accomplished by Hezekiah's scholarly team."),

    ("proverbs-30-to-31.md",
     "The final two chapters of Proverbs are revealed as prophecies of the last two eras of history: chapter 30 (authored by Agur) covers a time of war (2160-2280 AD) and chapter 31 (attributed to Lemuel's mother) describes the age of peace that follows. Proverbs 31, the portrait of the Wife of Noble Character, is read as a prophecy of the church at last fully mature — a community that also announces the complete liberation and enfranchisement of women, who will finally be respected and productive in every sphere. Strikingly, only the good times from Solomon's twenty-eight times appear in chapter 31, suggesting that the end of history will be characterized by flourishing for those who remain faithful. The article concludes with a moving personal note about the author's father, who died the week this chapter was being written, and whose lifelong insistence on wisdom set his son on the path that led to all these discoveries."),

    ("proverbs-4-to-19.md",
     "Proverbs chapters 4 through 19 are shown to constitute a prophetic clock in which each chapter corresponds to one of Solomon's twenty-eight times and to a 120-year era of history beginning in 960 BC — demonstrating that Proverbs is simultaneously practical wisdom for individuals and a prophetic timeline for civilizations. The article methodically matches each chapter's thematic content to its life phase (chapter 4 matching the time of being born, chapter 5 the time of dying, and so on through chapter 19) and to specific historical events in the corresponding era. The fulfilled prophecies demonstrate that God structures history by the same principles he uses to structure human lives, turning the history books into a training manual for wise living. This section constitutes one of the most thoroughgoing demonstrations of the Growth Pattern's prophetic accuracy across all twenty-eight phases, and supports the broader argument that Proverbs was carefully arranged — not haphazardly assembled — by editors who understood the wisdom pattern."),

    ("psalm-102.md",
     "Psalm 102, identified as written by King Hezekiah, is decoded as a prophetic clock structured according to Solomon's twenty-eight times, covering the same historical span as Solomon's Celestial Clock but with special prophetic focus on Islamic conquests of the Holy Land and their aftermath. The psalm's twenty-eight verses, extensive time-language, and use of themes from Ecclesiastes reflect Hezekiah's deep study of Solomon — the same king whose proverbs Hezekiah's team preserved. Hezekiah's personal experience of near-fatal illness and divine healing (receiving fifteen extra years of life) becomes a parable for Israel, which also appeared to be dying but received a reprieve. The mathematical key unlocking the connection is 816 = 8 x 102, the span in years from the Muslim capture of Jerusalem (637 AD) to the Fall of Constantinople (1453 AD), pointing the interpreter to this psalm as the prophetic text governing that era."),

    ("psalm-107.md",
     "Psalm 107 is revealed as a richly structured prophetic document organized in seven sections, each following a four-part rhythm of trouble, cry, rescue, and praise, mapping the history of the church from the Roman era to the end of the age. The psalm's central image of God gathering his scattered people from the four directions becomes a prophecy both of Israel's physical return to its land and of the gospel's expansion to every corner of the earth, with each of the seven sections matched to a specific historical era of Christian mission and expansion. The familiar refrain — 'Let them give thanks to the Lord for his unfailing love and his wonderful deeds for mankind' — repeated four times, structures the psalm around the number four (the four cardinal directions) while the Harvest Pattern governs the whole. The article argues that Psalm 107 is God's direct answer to the prayer at the close of Psalm 106 for the restoration of the exiles, making the two psalms a prophetic call-and-response spanning from the Babylonian exile to the Second Coming."),

    ("psalm-119.md",
     "Psalm 119, the Bible's longest chapter, is decoded as a prophetic clock in which each of its twenty-two Hebrew-alphabet stanzas corresponds to a 119-year generation of history, beginning with King David and extending to the present and beyond. The number 119 is shown to derive from 7 (completeness) multiplied by 17 (victory), encoded in the Genesis 8:4 reference to the ark resting on the seventeenth day of the seventh month — God's complete victory over evil at the flood. David's authorship is established by eight independent lines of evidence including linguistic patterns, royal themes, and parallels with confirmed Davidic psalms. The psalm's final verse — 'I have strayed like a lost sheep; seek your servant' — connects to the Good Shepherd imagery running from Ecclesiastes through Jesus' parables, framing all 176 verses as humanity's long cry to be found by the Shepherd of history."),

    ("quantification.md",
     "This article, part of the women's ordination series, applies Solomon's prophetic clock to determine precisely when God's plan for the liberation of women was scheduled to begin — and demonstrates that the scheduled time is already well in our past. Using the Growth Pattern's seven 480-year phases from the dedication of Solomon's temple in 960 BC, the author maps the time to be silent (680-1800 AD) and the time to speak (1800-1920 AD) to specific centuries, showing that the prophesied era of women's public ministry and ordination was inaugurated two hundred years ago. The Motherhood Pattern — a variant of the Growth Pattern specific to women's life phases, including conception, confinement, birth, and recovery — provides the biological and theological rationale for why women were temporarily restricted from leadership roles during the church's adolescent period. The conclusion is that Paul's instructions about women's silence were for a specific prophetic season, not a permanent divine decree, and that season has been over since the Great Awakening and the rise of women missionaries."),

    ("reconciliation.md",
     "This article, the culminating entry in the women's ordination series, provides both a spiritual sign and a literal sign to confirm that God's ordained season of women's liberation has arrived. The spiritual sign is the Protestant Reformation — interpreted as the Childbearing of 1 Timothy 2:15, giving birth to a new civilization — and the literal sign is the development of safe blood transfusions and the first antibiotic in 1928, which ended the era when childbirth itself was routinely fatal for women. Five consecutive times from Solomon's Growth Pattern (tear, mend, silent, speak, love) are matched to five historical eras from the Reformation to the present, each corresponding to a specific advance in women's liberation from the birth of Protestantism to the winning of the vote. The cumulative argument is that Scripture, history, and medicine all converge on the same verdict: the long season of women's subordination in the church has ended, and the time to love — marked by the equality of women in most spheres of life — has already begun."),
]

count = 0
for source, synopsis in updates:
    old = f"  source: {source}\n  synopsis: No synopsis yet"
    new = f"  source: {source}\n  synopsis: {synopsis}"
    if old in content:
        content = content.replace(old, new, 1)
        count += 1
    else:
        print(f"WARNING: could not find placeholder for {source}")

with open('/Users/Paul.Chernoch/Documents/GitHub/paulchernoch/source/synopsis.yaml', 'w') as f:
    f.write(content)

print(f"Updated {count} synopses.")
remaining = content.count('No synopsis yet')
print(f"Remaining placeholders: {remaining}")
